### ISSUE TITLE
Cannot acces WebAdmin from remote host

### ISSUE THREAD

**Issue by M4D-A** [nesfit/fitcrack#11]
How do I access WA from remote host?
After going under my Fitcrack server address in browser i can see login frontpage but after being redirected to dashboard i get 401 errors:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/35253296/97115422-e84c1c00-16f6-11eb-8ab9-f525b23ad857.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35253296/97115423-ea15df80-16f6-11eb-9560-baf7fbc8feff.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/35253296/97115425-ec783980-16f6-11eb-941b-78d7e10b6be2.png)
What should I change during instalation and what should i do after to be able to access WA?

**Comment by ihranicky** [comment]
The problem you report is connected to the same origin policy cookie settings in your web browser. Once you login, the backend returns a cookie with authentication token for the session. The token used to authorize all future requests. Since the backend and frontend run on different ports (5000 and 80 by defult), the two origins are different.

In Fitcrack, we solved this using CORS, which used to work for a long time. However, it seems the browsers are becoming by default more strict: https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/
So even with CORS enebled, the browser discards the cookie with the token if the connection is not done via HTTPS. And this is why you see this error. The backend is not considered as trusted which is pretty annoying.

I am trying to find a workaround since many people just want to download and test Fitcrack locally without installing a certificate, etc. I am open to any suggestions an ideas.

Currently, you can use one of the following solutions:
- Change the settings of your browser (network.cookie.sameSite.noneRequiresSecure in FF),
- Use a different browser,
- Use a "CORS anywhere" or similar plugin,
- Get a certificate and configure HTTPS to you Apache server (the proper way),
- Use the mod_proxy plugin and simulate the use of the same port.

**Comment by M4D-A** [comment]
Unfortunetaly browser-side solutions dont resolve the problem.
I have tried few different browsers with / without CORS manipulating extensions and while disabling security settings concerning CORS and cookies. Could you somehow cue me for a proper mod_proxy plugin configuration solution? Any tutorial or so?

**Comment by M4D-A** [comment]
Setting up https did the job. What is worth mentioning that self-signed certificates will NOT work, hence for example OpenSSL is won't suffice. It is required to have proper third-party certificate - Lets Encrypt provides easily accesible ones for free.

Thanks for help,
Regards, 
Adam
