### ISSUE TITLE
Daemons not starting

### ISSUE THREAD

**Issue by sscanavini** [nesfit/fitcrack#13]
Hi,
when I try to start the daemons with the ./bin/start this happens:
root@ariel:/home/boincadm/projects/fitcrack# ./bin/start
Entering ENABLED mode
Starting daemons
No daemons for this host found - check host name in config.xml

I tried to modify the config.xml label:
<host>localhost</host>

to:

<host>ariel.badnet.it</host>

But nothing happens. The hostname on which Fitcrack is installed is https://ariel.badnet.it.

What am I doing wrong?

EDIT: solved putting only "ariel" in the host label

**Comment by ihranicky** [comment]
Hi,
first, the `./bin/start` should be executed under the **boincadm** user instead of **root**. The entire `/home/boincadm/projects/fitcrack` with its contents should be owned and managed by the **boincadm** user.

 But it seems, there was some installation issue. Are the deamons compiled properly? In `/home/bóincadm/projects/fitcrack/bin`, there should be executables like **work_generator**, **assimilator**, and others. The **config.xml** just tells the control script what daemons to start and with which parameters - it is under the `<daemons>` section down in the file.
 
Also, when you install Fitcrack, the **URL_BASE** setting should be `http://ariel.badnet.it/` or `https://ariel.badnet.it/login` if you are running HTTPS.

Best regards
Radek

**Comment by ihranicky** [comment]
Also see issue https://github.com/nesfit/fitcrack/issues/15 where I explain the **URL_BASE** and please let me know if that helped. If this is the cause, I will update the README to cover the issue.

**Comment by davidbolvansky** [comment]
Closed. Reopen if not working for you.
