### ISSUE TITLE
Host not added

### ISSUE THREAD

**Issue by sscanavini** [nesfit/fitcrack#14]
Hi,
I've tried to add an host, everything is fine client side, I can see the confirmation but on server side no hosts are added.
BOINC manager shows the project correctly.

**Comment by ihranicky** [comment]
Hi, I believe this is connected to this issue: https://github.com/nesfit/fitcrack/issues/13
Fitcrack webadmin loads the host info from a mySQL table called `host` (note: do not confuse with `fc_host`) - you can check if there is any record there. The contents of the `host` are maintaned by BOINC and its daemons. Since those are not running, the host was not added to the database.

**Comment by davidbolvansky** [comment]
Closed. Reopen if not working for you.
