### ISSUE TITLE
Large Dictionary Cannot be Imported

### ISSUE THREAD

**Issue by NHAS** [nesfit/fitcrack#42]
I have tried to add the OneWordlistToListThemAll.txt (99gb) using the "Add from server" functionally this generates the error "An unhandled accepted exception has occurred". 

Sometimes this will result in a wordlist being added, but unusable, this includes being unable to delete the entry that was created. Other times nothing happens. 

![image](https://user-images.githubusercontent.com/6820641/173021907-d89d5c11-d499-4ea8-b97c-e5a18df1be20.png)

![image](https://user-images.githubusercontent.com/6820641/173021878-f0049403-a0a1-457a-9ce4-3a9b6f1af021.png)

![image](https://user-images.githubusercontent.com/6820641/173021847-d42e7333-4054-4a1a-8f55-01fc4d67b9ac.png)

![image](https://user-images.githubusercontent.com/6820641/173021938-4c15e6ab-e0cb-4c4f-8e93-4f4e40ad2b7b.png)

**Comment by NHAS** [comment]
I didnt upload the dictionary via the web interface. I put it in the import directory on the server, then tried to use the web interface to trigger the import. 

Then it died. 

Thanks for getting back to me so fast!

**Comment by davidbolvansky** [comment]
Can you share outpur of

“cat /var/log/apache2/error.log”

?

**Comment by lachlan2k** [comment]
I've been able to replicate this issue.

The problem is, large wordlists take some time to import. The HTTP requests time out (503), but the import will indeed succeed after a (long) while. However, to the user, it appears to fail due to the timed out request.

So, I discovered that you get the unhandled exception when 2 dictionaries are importing **simultaneously**. The error is as follows:

```
File "/var/www/html/fitcrackAPI/src/src/api/fitcrack/end points/dictionary/dictionary.py", line 213, 
hc_keyspace = int(shellExec(HASHCAT_PATH + ' --keyspac e -a 0 ' + newPath, cwd=HASHCAT_DIR)) 
ValueError: invalid literal for int() with base 10: ''
```
Hashcat is being used to count the lines in the file, however it is clearly outputting something weird.
This seems strange, so I tried running the command myself, and the problem is good ol' hashcat and its sessions...
```
[root@localhost lachlan]# /bin/sh -c "/var/www/html/fitcrackAPI/src/../hashcat/hashcat.bin --keyspace -a 0 /usr/share/collections/dictionaries/test_xxxxxxx.txt"
Already an instance '/var/www/html/fitcrackAPI/hashcat/hashcat.bin' running on pid 148239
```

**My Recommendations**
* I don't think it's necessary to use hashcat to calculate line-count here, it doesn't provide any useful features. `wc -l <path>` should be sufficient for a quick fix.
* However, a better solution would be to add a line counter to `pwd_dist`, as this should save significant I/O by doing all this work in one operation.
* Just for sanity: make sure 64-bit+ longs are used for storing the sizes in all places. The dictionary I'm testing with, weakpass_3a, is `9,791,385,482` lines long. A signed 32-bit integer stores up to only `2,147,483,647`.
* Ideally, the HTTP request to import from local file should merely *start* the import procedure and return instantly. Large imports might take 20+ minutes. The UI should display a message saying "Please check back later" and ideally show a "pending import" row or similar.

**Comment by NHAS** [comment]
Thank you @lachlan2k you're awesome! 

My preference would be towards having a page that tracks the import process. But for now, I'd be quite keen on just having a patch that lets me import big libraries. Fancy UI can come later.

**Comment by davidbolvansky** [comment]
Thanks for detailed analysis! Amazing :)

`hc_keyspace = int(shellExec(HASHCAT_PATH + ' --keyspac e -a 0 ' + newPath, cwd=HASHCAT_DIR))`

Yeah, this is useless now, as we can get keyspace from password distribution data.
Implemented: https://github.com/nesfit/fitcrack/commit/436dd498c2c32449ca91cd2d7b5f267a40af9c03

>> Ideally, the HTTP request to import from local file should merely start the import procedure and return instantly. 

Already works this way, no? Pick file, click on Upload. Then click outside this "popup" window (maybe this is not obvious step?).  You can go to Jobs, create new job, etc... After some time, you will get an notification (bottom right part of screen) that your dictionary was uploaded.

I tried it with 2 GB file and it worked the way I described above.

>> The UI should display a message saying "Please check back later" and ideally show a "pending import" row or similar.

Yes, I agree that it could be improved even futher.

**Comment by lachlan2k** [comment]
Thanks for the patch! Can you also please add it to `/fromFile`? Copy-pasting the same patch works.

> Please retest with your dictionary.
It imports much faster now, and concurrent imports work without errors!

> Already works this way, no? Pick file, click on Upload. Then click outside this "popup" window (maybe this is not obvious step?). You can go to Jobs, create new job, etc... After some time, you will get an notification (bottom right part of screen) that your dictionary was uploaded.

For the file upload option, yes, the user interface design works fine. However, the "add from server" option gives very little indication of what's happening during a long import.

More importantly though, for both upload and "add from server", if the wordlist is large enough that processing takes > 60 seconds, Apache will send a 504 timeout, and the UI has no idea what's happening.

What I believe both myself and @NHAS are suggesting is:  When performing "add from server", instead of waiting for the import to finish, the server should immediately reply saying "Okay, import started", 

> I currently dont know if there is any place where this is broken, please give us know if you found some broken place.

I haven't experienced any issues, just left that as a note for any possible patches :)

**Comment by davidbolvansky** [comment]
Ah yes, server browser :/ horrible UI there!

I did small fixes to make it less broken. Not sure about timeouts, probably still broken.

https://github.com/nesfit/fitcrack/commit/ffe1b1cfae53144184fedbbc7fdb6edc889c8db1

**Comment by davidbolvansky** [comment]
Please close if you can import large dictionary now.

**Comment by lachlan2k** [comment]
I had a brief look yesterday and tried it on some medium-sized lists and it worked. We'll give it a try today on the massive lists then close the issue if it works!

Thanks once again for all of your help, Dávid.

**Comment by NHAS** [comment]
Yes, this has fixed the issue! Thanks
