### ISSUE TITLE
Docker install error: "failed to solve: Process "./update_client_bins.sh" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by Pareid0lia** [nesfit/fitcrack#65]
Recently trying to install fitcrack on an oracle cloud instance and keep getting the following error:
`
```
#0 236.9 x86_64-w64-mingw32-g++ -I'./include/' -I'./include/boinc/' -I'./include/libzip/' -DGIT_REV="\"\"" -Werror -Wall -Wextra -O3 -g3 -std=c++11 -c src/main.cpp -o obj/main.o
#0 40391.1 x86_64-w64-mingw32-g++: fatal error: Killed signal terminated program cc1plus
#0 40391.1 compilation terminated.
#0 40391.7 make: *** [Makefile:45: obj/main.o] Error 1
#0 40394.5 objcopy: './bin/runner.exe': No such file
#0 40394.8 objcopy: './bin/runner.exe': No such file
#0 40394.9 rm: cannot remove './bin/runner.exe': No such file or directory
------
Dockerfile:124
--------------------
 122 |     RUN apt-get install -y g++-mingw-w64-x86-64
 123 |     RUN chmod +x ./update_client_bins.sh
 124 | >>> RUN bash ./update_client_bins.sh
 125 |
 126 |     WORKDIR /srv/fitcrack/
--------------------
ERROR: failed to solve: process "/bin/sh -c bash ./update_client_bins.sh" did not complete successfully: exit code: 1
ubuntu@<SERVERNAME>:~/fitcrack$ 
```
Server details:
Ubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-1029-oracle

Its seems that something is terminating the compilation?

**Comment by davidbolvansky** [comment]
x86_64-w64-mingw32-g++: fatal error: Killed signal terminated program cc1plus

seems kinda weird, compiler crashed..

https://github.com/nesfit/fitcrack/blob/master/runner/update_client_bins.sh#L9

try to remove lines 9 - 13.

**Comment by nullalloc** [comment]
Seems that due to the limited memory and cpu, compiling something that needs alot of resources causes considirable slowdown of the server, to the point that the OS will search for what is using the most resources and issue it to terminate.
[SRC](https://stackoverflow.com/a/35011967)

The fix you suggested seems to have worked!

However now the machine is stuck on vite building.

=> [65/69] RUN export PATH=/usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/b  9170.2s
 => => # npm notice Run `npm install -g npm@9.5.1` to update!                                                                         
 => => # npm notice                                                                                                                   
 => => # > fitcrack@2.4.0 build                                                                                                       
 => => # > vite build                                                                                                                 
 => => # vite v2.6.14 building for production...                                                                                      
 => => # transforming...                                                                                                              
ubuntu@<SERVERNAME>:~/fitcrack$``

there is no error code, Im just throw to the commandline.

(note that it may be taking alot of resources when vite is building/transforming, seems that it is utilizing so much that the SSH session dies out. But I am able to reconnect after it seems that the job is ended/terminated.)

**Comment by Pareid0lia** [comment]
Changed the server from ubuntu to debian 11, now getting more info:
`#0 43.94
#0 43.94 6 vulnerabilities (3 moderate, 2 high, 1 critical)
#0 43.94
#0 43.94 To address all issues, run:
#0 43.94   npm audit fix
#0 43.94
#0 43.94 Run 'npm audit' for details.
#0 43.94 npm notice
#0 43.94 npm notice New major version of npm available! 8.5.5 -> 9.6.1
#0 43.94 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
#0 43.94 npm notice Run `npm install -g npm@9.6.1` to update!
#0 43.94 npm notice
#0 45.26
#0 45.26 > fitcrack@2.4.0 build
#0 45.26 > vite build
#0 45.26
#0 46.96 vite v2.6.14 building for production...
#0 47.14 transforming...
#0 100.1 ✓ 880 modules transformed.
#0 119324.8 rendering chunks...
#0 181502.3 Killed
------
Dockerfile:141
--------------------
 140 |     WORKDIR /srv/fitcrack/webadmin/fitcrackFE
 141 | >>> RUN export PATH=/usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin:$PATH \
 142 | >>> && npm ci && npm run build
 143 |
--------------------
ERROR: failed to solve: process "/bin/sh -c export PATH=/usr/local/lib/nodejs/node-v16.15.0-linux-x64/bin:$PATH && npm ci && npm run build" did not complete successfully: exit code: 137
ERROR: Service 'fitcrack_server' failed to build : Build failed
debian@<SERVERNAME>:~/fitcrack$ 
`
Could'nt find a reason for the `#0 181502.3 Killed`.

Any suggestions?

**Comment by davidbolvansky** [comment]
Exit code 137 says that the root is same, limited  memory… overall this a real problem and even if you build everything successfully, things will fail on runtime due to low memory.

**Comment by Pareid0lia** [comment]
This issue is indeed with low memory as the server I was trying to install it on only has 1 core and 1 Gb of ram, running it on another server with 2 cores and 4Gb RAM worked, overall this issue stems from lack of resources and its solution is to get a stronger machine.
